name: Reusable Flow
on: [workflow_dispatch]

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v4
        with:
          repository: Anshita-Bhasin/cypress-pom-bdd


      - name: Run Cypress Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:smoke-critical:firefox-browser
          

