name: Test with report
on:
  push:
    branches:
      - main

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v4

      - name: Run Cypress Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run smoketest-withreport
          browser: chrome

      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
         name: Mochawesome HTML Report - Reg Flow
         path: /reports/*     

      - name: fail reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
           name: cypress-screenshots
           path: /reports/*
           run : echo ' test failed'

      - name: pass reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
           name: cypress-report
           run:  echo ' always run'
