name: Test with report
on:
  push:
    branches:
      - main

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v4

      - name: Run Cypress Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run smoketest-withreport
          browser: chrome

      - name: reports
        uses: actions/upload-artifact@v4

      - name: fail reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
           name: cypress-screenshots
           path: ./cypress/screenshots

      - name: fail reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
           name: cypress-videos
           path: ./cypress/videos
